# Generated by Django 5.1.2 on 2024-10-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourisme_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image_couverture',
            field=models.ImageField(blank=True, null=True, upload_to='couverture_image'),
        ),
    ]
