# Generated by Django 5.1.2 on 2024-10-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourisme_app', '0003_presentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='presentations_images/'),
        ),
    ]
