# Generated by Django 5.1.2 on 2024-11-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourisme_app', '0010_article_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baniere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='baniere')),
            ],
        ),
    ]
