# Generated by Django 5.1.2 on 2024-11-13 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourisme_app', '0011_baniere'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Baniere',
        ),
    ]
