# Generated by Django 5.1.2 on 2024-11-13 11:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourisme_app', '0012_delete_baniere'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baniere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('content', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='baniere')),
            ],
        ),
    ]
