# Generated by Django 5.1.2 on 2024-11-13 13:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourisme_app', '0013_baniere'),
    ]

    operations = [
        migrations.AddField(
            model_name='baniere',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
