# Generated by Django 5.1.2 on 2024-11-13 16:17

import ckeditor.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourisme_app', '0014_baniere_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='destination')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
