# Generated by Django 5.1.2 on 2024-11-14 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourisme_app', '0015_destination'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
