# Generated by Django 5.1.2 on 2024-12-18 23:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourisme_app', '0017_activity_banieredestination_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('privacy_policy', 'Politique de confidentialité'), ('terms_of_use', "Conditions d'utilisation"), ('legal_notice', 'Mentions légales')], max_length=255, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('content', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Document juridique',
                'verbose_name_plural': 'Documents juridiques',
            },
        ),
    ]
